baseurl = "http://thisneedstobereplaced.tld"
languageCode = "en-us"
title = "CFOps"
theme = "cf"

[params]
  description = "Cloud Foundry Operations Tool"

[[params.actionlink]]
    title = "github"
    icon = "github"
    url = "https://github.com/pivotalservices/cfops"

[[params.actionlink]]
    title = "download"
    icon = "cloud-download"
    url = "https://github.com/pivotalservices/cfops/releases"

[[params.social]]
    title = "github"
    icon = "github"
    url = "https://github.com/pivotalservices/cfops"

[[params.social]]
    title = "gitter"
    icon = "comment"
    url = "https://gitter.im/pivotalservices/cfops"
